plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id "com.modrinth.minotaur" version "2.+"
    id "net.darkhax.curseforgegradle" version "1.1.+"
}

base {
    archivesName = "CrashAssistant-${project.name}-1.21.5-1.21.11"
}

configurations {
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    compileOnly files("${rootProject.projectDir}/app_common-config_libs/common_config_1_18_2__upper.jar")
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier.set('dev-shadow')
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn tasks.shadowJar
    from zipTree("${rootProject.projectDir}/app_common-config_libs/common_config_1_18_2__upper.jar")
    from zipTree(tasks.shadowJar.archiveFile.get().asFile)
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

def publishingGameVersions = [
        "1.21.5",
        "1.21.6",
        "1.21.7",
        "1.21.8",
        "1.21.9",
        "1.21.10",
        "1.21.11"
]
def parsedChangelog = file('../changelog.md').text.replaceAll(/\r\n|\r/, '\n').split(/(?:^|\n\n)\S.*?(?:\n\n|$)/)[1].trim() +
        "\n\n### [See full changelog](https://kostromdan.github.io/Crash-Assistant/changelog.md)"

if (System.getenv("MODRINTH_TOKEN") != null) {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = "ix1qq8Ux"
        versionNumber = project.version
        versionName = tasks.remapJar.archiveFile.get().asFile.name
        versionType = release_type
        changelog = parsedChangelog
        uploadFile = tasks.remapJar
        gameVersions = publishingGameVersions
        loaders = ["fabric", "quilt"]
    }
}

if (System.getenv("CF_TOKEN") != null) {
    tasks.register("publishCurseForge", net.darkhax.curseforgegradle.TaskPublishCurseForge) {
        group = "upload"
        apiToken = System.getenv("CF_TOKEN")

        def mainFile = upload("1154099", tasks.remapJar)
        mainFile.displayName = tasks.remapJar.archiveFile.get().asFile.name
        mainFile.changelog = parsedChangelog
        mainFile.changelogType = "markdown"
        mainFile.releaseType = release_type

        mainFile.addGameVersion(*publishingGameVersions)
        mainFile.addEnvironment("Client")
        mainFile.addModLoader("Fabric", "Quilt")
    }
}

task publishUnified {
    group = "upload"
    if (System.getenv("MODRINTH_TOKEN") != null) dependsOn(tasks.modrinth)
    if (System.getenv("CF_TOKEN") != null) dependsOn(tasks.publishCurseForge)
}

task publishUnifiedToLocal(type: Copy) {
    group = "upload"
    dependsOn(tasks.remapJar)
    from(tasks.remapJar.archiveFile)
    into("build/unified-local/project0")
}
