plugins {
    id 'com.github.johnrengelman.shadow'
    id "com.modrinth.minotaur" version "2.+"
    id "net.darkhax.curseforgegradle" version "1.1.+"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

shadowJar {
    archiveClassifier.set('dev-shadow')
    configurations = [project.configurations.shadowBundle]
}

remapJar {
    from zipTree("${rootProject.projectDir}/app_common-config_libs/common_config_1_18_2__upper.jar")
    input.set shadowJar.archiveFile
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

def publishingGameVersions = ["1.18.2"]
def parsedChangelog = file('../changelog.md').text.replaceAll(/\r\n|\r/, '\n').split(/(?:^|\n\n)\S.*?(?:\n\n|$)/)[1].trim() +
        "\n\n### [See full changelog](https://kostromdan.github.io/Crash-Assistant/changelog.md)"

if (System.getenv("MODRINTH_TOKEN") != null) {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = "ix1qq8Ux"
        versionNumber = mod_version
        versionName = tasks.remapJar.archiveFile.get().asFile.name
        versionType = release_type
        changelog = parsedChangelog
        uploadFile = tasks.remapJar
        gameVersions = publishingGameVersions
        loaders = ["fabric", "quilt"]
    }
}

if (System.getenv("CF_TOKEN") != null) {
    tasks.register("publishCurseForge", net.darkhax.curseforgegradle.TaskPublishCurseForge) {
        group = "upload"
        apiToken = System.getenv("CF_TOKEN")

        def mainFile = upload("1154099", tasks.remapJar)
        mainFile.displayName = tasks.remapJar.archiveFile.get().asFile.name
        mainFile.changelog = parsedChangelog
        mainFile.changelogType = "markdown"
        mainFile.releaseType = release_type

        mainFile.addGameVersion(*publishingGameVersions)
        mainFile.addEnvironment("Client")
        mainFile.addModLoader("Fabric", "Quilt")
    }
}

task publishUnified {
    group = "upload"
    if (System.getenv("MODRINTH_TOKEN") != null) dependsOn(tasks.modrinth)
    if (System.getenv("CF_TOKEN") != null) dependsOn(tasks.publishCurseForge)
}

task publishUnifiedToLocal(type: Copy) {
    group = "upload"
    dependsOn(tasks.remapJar)
    from(tasks.remapJar.archiveFile)
    into("build/unified-local/project0")
}
