dependencies {
	implementation project(':common')
	
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

base {
	archivesName = "CrashAssistant-${project.name}-26.1"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

jar {
	from project(':common').sourceSets.main.output
	from zipTree("${rootProject.projectDir}/26_1_libs/common_config.jar")
}
