plugins {
    id 'java'
    id "me.shedaniel.unified-publishing" version "0.1.+"
    id 'xyz.wagyourtail.unimined' version '1.4.1'
}

group 'dev.kostromdan.mods.crash_assistant'

base {
    archivesName = '!!!CrashAssistant-' + minecraft_version
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}


sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

sourceSets {
    fabric {
        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
    forge {
        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
}

repositories {
    maven {
        name = "wagyourtail releases"
        url = "https://maven.wagyourtail.xyz/releases"
    }
    maven {
        name = "sponge"
        url = "https://repo.spongepowered.org/maven"
    }
    mavenCentral()
}

unimined.minecraft {
    version project.minecraft_version

    mappings {
        searge()
        mcp("stable", "12-1.7.10")
    }

    defaultRemapJar = false
}

unimined.minecraft(sourceSets.fabric) {
    combineWith(sourceSets.main)

    legacyFabric {
        loader project.fabric_version
    }

    defaultRemapJar = true
}

unimined.minecraft(sourceSets.forge) {
    combineWith(sourceSets.main)

    minecraftForge {
        loader project.forge_version
//        mixinConfig "modid.mixins.json"
    }

    defaultRemapJar = true
}

configurations {
    mainImplementation
    implementation {
        extendsFrom forgeImplementation
        extendsFrom fabricImplementation
    }
}

sourceSets {
    main {
        compileClasspath += configurations.mainImplementation
        runtimeClasspath += configurations.mainImplementation
    }
}

dependencies {
    implementation files("${rootProject.projectDir}/app_common-config_libs/common_config_1_7_10.jar")
    forgeImplementation files("${rootProject.projectDir}/app_common-config_libs/common_config_1_7_10.jar")
}

[forgeJar, fabricJar].each { task ->
    task.configure {
        from zipTree("${rootProject.projectDir}/app_common-config_libs/common_config_1_7_10.jar")
    }
}

forgeJar {
    manifest {
        attributes([
                'FMLCorePluginContainsFMLMod': 'true',
                'FMLCorePlugin'              : 'dev.kostromdan.mods.crash_assistant.forge_coremod.CrashAssistantEntrypoint'
        ])
    }
}

def configureJarNames() {
    def jarConfigurations = [
            remapForgeJar : "!!!CrashAssistant-forge-${minecraft_version}-${version}.jar",
            remapFabricJar: "CrashAssistant-fabric-${minecraft_version}-${version}.jar",
            forgeJar      : "!!!CrashAssistant-forge-${minecraft_version}-${version}-dev.jar",
            fabricJar     : "CrashAssistant-fabric-${minecraft_version}-${version}-dev.jar"
    ]

    jarConfigurations.each { taskName, fileName ->
        tasks.named(taskName) {
            archiveFileName = fileName
        }
    }
}

configureJarNames()

jar {
    enabled = false
}

processFabricResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

processForgeResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }

    filesMatching("mcmod.info") {
        expand "version": project.version
    }
}

unifiedPublishing {
    project {
        gameVersions = [minecraft_version]
        gameLoaders = ["forge"]

        displayName = tasks.remapForgeJar.archiveFile.get().asFile.name
        version = rootProject.version
        changelog = file('changelog.md').text.replaceAll(/\r\n|\r/, '\n').split(/(?:^|\n\n)\S.*?(?:\n\n|$)/)[1].trim() +
                "\n\n### [See full changelog](https://kostromdan.github.io/Crash-Assistant/changelog.md)"
        releaseType = release_type

        mainPublication tasks.remapForgeJar

        var cfToken = System.getenv("CF_TOKEN")
        if (cfToken != null) {
            curseforge {
                token = cfToken
                id = "1154099"
            }
        }

        var mrToken = System.getenv("MODRINTH_TOKEN")
        if (mrToken != null) {
            modrinth {
                token = mrToken
                id = "ix1qq8Ux"
            }
        }
    }
}