plugins {
    id 'java-base'
}

apply plugin: 'idea'

def appProject = project(':app')
def appRunLauncher = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(8)
}

def registerAppMainRunTask = { String taskName, String mainClassName, Map<String, String> systemProperties = [:] ->
    tasks.register(taskName, JavaExec) {
        group = 'application'
        description = "Runs ${mainClassName}"

        dependsOn appProject.tasks.named('classes')
        dependsOn appProject.tasks.named('compileJava9Java')

        classpath = appProject.sourceSets.main.runtimeClasspath +
                appProject.sourceSets.main.output +
                appProject.sourceSets.java9.output
        mainClass = mainClassName
        javaLauncher = appRunLauncher
        maxHeapSize = '512m'
        workingDir = rootDir
        if (!systemProperties.isEmpty()) {
            systemProperties.each { key, value ->
                systemProperty(key, value)
            }
        }
    }
}

registerAppMainRunTask(
        'runCrashAssistantAppLicensed',
        'dev.kostromdan.mods.crash_assistant.app.CrashAssistantApp',
        ['minecraft.launch.arguments': '--username KostromDan --uuid a23d9d090e254763aa13f7e8e8715812']
)
registerAppMainRunTask(
        'runCrashAssistantAppOfflineMode',
        'dev.kostromdan.mods.crash_assistant.app.CrashAssistantApp',
        ['minecraft.launch.arguments': '--username KostromDan --uuid a23d9d090e254763aa13f7e8e8715813']
)
registerAppMainRunTask('runIntegratedGPUWarning', 'dev.kostromdan.mods.crash_assistant.app.gui.IntegratedGPUWarning')
registerAppMainRunTask('runIntelChipBugWarning', 'dev.kostromdan.mods.crash_assistant.app.gui.IntelChipBugWarning')

idea {
    module {
        downloadSources = true
    }
}


task collectJars(type: Copy) {
    dependsOn(
            ":jar_generation:common_config_1_7_10:shadowJar",
            ":jar_generation:common_config_1_8__1_16_5:shadowJar",
            ":jar_generation:common_config_1_17__1_18_1:shadowJar",
            ":jar_generation:common_config_1_18_2__upper:shadowJar",
    )

    doFirst {
        def outDir = file("$rootDir/app_common-config_libs")
        if (outDir.exists()) {
            outDir.deleteDir()
        }
        outDir.mkdirs()
    }

    from("jar_generation/common_config_1_7_10/build/libs") {
        include '*.jar'
    }
    from("jar_generation/common_config_1_8__1_16_5/build/libs") {
        include '*.jar'
    }
    from("jar_generation/common_config_1_17__1_18_1/build/libs") {
        include '*.jar'
    }
    from("jar_generation/common_config_1_18_2__upper/build/libs") {
        include '*.jar'
    }

    into("$rootDir/app_common-config_libs")
}

build.finalizedBy(collectJars)

clean {
    delete "$rootDir/app_common-config_libs"
}
