plugins {
    id 'java'
    id "me.shedaniel.unified-publishing" version "0.1.+"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

unifiedPublishing {
    project {
        gameVersions = [rootProject.minecraft_version]
        gameLoaders = ["fabric"]

        displayName = rootProject.tasks.remapFabricJar.archiveFile.get().asFile.name
        version = rootProject.version
        changelog = file('changelog.md').text.replaceAll(/\r\n|\r/, '\n').split(/(?:^|\n\n)\S.*?(?:\n\n|$)/)[1].trim() +
                "\n\n### [See full changelog](https://kostromdan.github.io/Crash-Assistant/changelog.md)"
        releaseType = release_type

        mainPublication rootProject.tasks.remapFabricJar

        var cfToken = System.getenv("CF_TOKEN")
        if (cfToken != null) {
            curseforge {
                token = cfToken
                id = "1154099"
            }
        }

        var mrToken = System.getenv("MODRINTH_TOKEN")
        if (mrToken != null) {
            modrinth {
                token = mrToken
                id = "ix1qq8Ux"
            }
        }
    }
}