package dev.kostromdan.mods.crash_assistant.common_config.mod_list;

import org.apache.commons.jexl3.annotations.NoJexl;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Locale;
import java.util.Map;

/**
 * Reads every modlist.txt format generated by Crash Assistant so far.
 *
 * <p>Jar-in-jar rows are intentionally ignored. History snapshots contain the
 * top-level mod set and the count written at the beginning of modern files also
 * describes that set.</p>
 */
@NoJexl
public final class ModListTxtParser {
    private static final String COUNT_PREFIX = "Mods count:";
    private static final long MAX_IMPORT_BYTES = 16L * 1024L * 1024L;
    private static final int MAX_IMPORT_CHARS = 16 * 1024 * 1024;
    private static final int MAX_TOP_LEVEL_MODS = 4096;

    private ModListTxtParser() {
    }

    public static LinkedHashSet<Mod> parse(Path path) throws IOException {
        if (path == null) {
            throw new ModListTxtParseException("No modlist.txt file was selected.");
        }
        long size = Files.size(path);
        if (size > MAX_IMPORT_BYTES) {
            throw new ModListTxtParseException("The modlist.txt is too large (maximum 16 MiB).");
        }
        return parse(new String(readBounded(path), StandardCharsets.UTF_8));
    }

    public static LinkedHashSet<Mod> parse(String text) throws ModListTxtParseException {
        if (text == null) {
            throw new ModListTxtParseException("The modlist.txt contents are missing.");
        }
        if (text.length() > MAX_IMPORT_CHARS) {
            throw new ModListTxtParseException("The modlist.txt is too large (maximum 16 MiB).");
        }

        String normalized = text.replace("\r\n", "\n").replace('\r', '\n');
        if (!normalized.isEmpty() && normalized.charAt(0) == '\ufeff') {
            normalized = normalized.substring(1);
        }

        String[] lines = normalized.split("\n", -1);
        int first = firstContentLine(lines, 0);
        if (first < 0) {
            throw new ModListTxtParseException("The modlist.txt is empty.");
        }

        Integer expectedCount = null;
        if (lines[first].trim().startsWith(COUNT_PREFIX)) {
            expectedCount = parseCount(lines[first].trim());
            if (expectedCount.intValue() > MAX_TOP_LEVEL_MODS) {
                throw tooManyTopLevelMods();
            }
            first = firstContentLine(lines, first + 1);
            if (first < 0) {
                if (expectedCount == 0) {
                    return new LinkedHashSet<Mod>();
                }
                throw new ModListTxtParseException("The modlist.txt does not contain any mod rows.");
            }
        }

        LinkedHashSet<Mod> result;
        if (looksLikeTableHeader(lines[first])) {
            result = parseTable(lines, first);
        } else if (expectedCount != null) {
            result = parseDetailedLegacy(lines, first);
        } else {
            result = parseSimpleLegacy(lines, first);
        }

        if (expectedCount != null && expectedCount.intValue() != result.size()) {
            throw new ModListTxtParseException(
                    "The declared mod count is " + expectedCount + ", but " + result.size() + " mod rows were parsed.");
        }
        return result;
    }

    private static Integer parseCount(String line) throws ModListTxtParseException {
        String value = line.substring(COUNT_PREFIX.length()).trim();
        try {
            int count = Integer.parseInt(value);
            if (count < 0) {
                throw new NumberFormatException("negative");
            }
            return count;
        } catch (NumberFormatException e) {
            throw new ModListTxtParseException("Invalid mod count: " + value, e);
        }
    }

    private static LinkedHashSet<Mod> parseTable(String[] lines, int headerIndex)
            throws ModListTxtParseException {
        String[] headerCells = splitTableLine(lines[headerIndex]);
        Map<String, Integer> columns = new HashMap<String, Integer>();
        for (int i = 0; i < headerCells.length; i++) {
            columns.put(normalizeHeader(headerCells[i]), i);
        }

        Integer jarIndex = firstColumn(columns, "jar name", "jarname");
        if (jarIndex == null) {
            throw new ModListTxtParseException("The table has no jar name column.");
        }

        LinkedHashSet<Mod> result = new LinkedHashSet<Mod>();
        int topLevelRows = 0;
        for (int i = headerIndex + 1; i < lines.length; i++) {
            String line = lines[i];
            if (line.trim().isEmpty() || isSeparator(line)) {
                continue;
            }
            if (line.indexOf('|') < 0) {
                throw new ModListTxtParseException("Invalid table row at line " + (i + 1) + ".");
            }

            String[] cells = splitTableLine(line);
            if (jarIndex.intValue() >= cells.length) {
                throw new ModListTxtParseException("Missing jar name at line " + (i + 1) + ".");
            }

            String rawJarCell = cells[jarIndex.intValue()];
            if (!rawJarCell.isEmpty() && Character.isWhitespace(rawJarCell.charAt(0))) {
                // The writer indents informational Jar-in-Jar entries and prefixes their
                // archive-internal path. They never become actionable top-level mods.
                continue;
            }

            String jarName = rawJarCell.trim();
            if (jarName.isEmpty()) {
                throw new ModListTxtParseException("Empty jar name at line " + (i + 1) + ".");
            }
            validateJarName(jarName, i + 1);
            topLevelRows = countTopLevelRow(topLevelRows);

            String notes = cell(cells, columns, "notes");
            String mCreatorCell = cell(cells, columns, "ismcreator");
            String connectorCell = cell(cells, columns, "isloadedbyconnector");
            String modId = firstCell(cells, columns, "mod id", "mod id (ismcreator)");
            boolean mCreator = containsIgnoreCase(notes, "mcreator")
                    || containsIgnoreCase(mCreatorCell, "mcreator")
                    || containsIgnoreCase(modId, "mcreator mod");
            boolean connector = containsIgnoreCase(notes, "connector")
                    || containsIgnoreCase(connectorCell, "connector");
            modId = removeMarker(modId, "(MCreator mod)");

            String name = cell(cells, columns, "mod name");
            String version = cell(cells, columns, "mod version");
            String mixinsCell = cell(cells, columns, "mixin configs");
            String modrinthHash = emptyToNull(cell(cells, columns, "modrinth hash"));
            Long curseForgeHash = parseLongOrNull(cell(cells, columns, "curseforge hash"), i + 1);

            HashSet<String> mixins = new HashSet<String>();
            if (!mixinsCell.isEmpty()) {
                for (String mixin : mixinsCell.split(",\\s*")) {
                    if (!mixin.trim().isEmpty()) {
                        mixins.add(mixin.trim());
                    }
                }
            }

            result.add(new Mod(
                    jarName,
                    emptyToNull(modId),
                    emptyToNull(name),
                    emptyToNull(version),
                    mCreator ? Boolean.TRUE : null,
                    connector ? Boolean.TRUE : null,
                    mixins,
                    new ArrayList<Mod>(),
                    null,
                    curseForgeHash,
                    modrinthHash));
        }
        return result;
    }

    private static LinkedHashSet<Mod> parseDetailedLegacy(String[] lines, int first)
            throws ModListTxtParseException {
        LinkedHashSet<Mod> result = new LinkedHashSet<Mod>();
        int topLevelRows = 0;
        for (int i = first; i < lines.length; i++) {
            String raw = lines[i];
            String trimmed = raw.trim();
            if (trimmed.isEmpty() || raw.length() != trimmed.length()) {
                // Old detailed files use indentation for mixins, headings and jar-in-jar entries.
                continue;
            }
            if ("mixins:".equalsIgnoreCase(trimmed) || "jarjar:".equalsIgnoreCase(trimmed)) {
                continue;
            }
            topLevelRows = countTopLevelRow(topLevelRows);
            result.add(parseLegacyModLine(trimmed, i + 1));
        }
        return result;
    }

    private static LinkedHashSet<Mod> parseSimpleLegacy(String[] lines, int first)
            throws ModListTxtParseException {
        LinkedHashSet<Mod> result = new LinkedHashSet<Mod>();
        int topLevelRows = 0;
        for (int i = first; i < lines.length; i++) {
            String line = lines[i].trim();
            if (line.isEmpty()) {
                continue;
            }
            topLevelRows = countTopLevelRow(topLevelRows);
            Mod mod = parseLegacyModLine(line, i + 1);
            if (!looksLikeTopLevelEntry(mod.getJarName())) {
                throw new ModListTxtParseException("Unrecognized legacy modlist row at line " + (i + 1) + ".");
            }
            result.add(mod);
        }
        if (result.isEmpty()) {
            throw new ModListTxtParseException("The modlist.txt does not contain any mod rows.");
        }
        return result;
    }

    private static byte[] readBounded(Path path) throws IOException {
        ByteArrayOutputStream output = new ByteArrayOutputStream(8192);
        byte[] buffer = new byte[8192];
        long total = 0L;
        try (InputStream input = Files.newInputStream(path)) {
            int read;
            while ((read = input.read(buffer)) >= 0) {
                if (read == 0) {
                    continue;
                }
                total += read;
                if (total > MAX_IMPORT_BYTES) {
                    throw new ModListTxtParseException("The modlist.txt is too large (maximum 16 MiB).");
                }
                output.write(buffer, 0, read);
            }
        }
        return output.toByteArray();
    }

    private static int countTopLevelRow(int currentCount) throws ModListTxtParseException {
        if (currentCount >= MAX_TOP_LEVEL_MODS) {
            throw tooManyTopLevelMods();
        }
        return currentCount + 1;
    }

    private static ModListTxtParseException tooManyTopLevelMods() {
        return new ModListTxtParseException(
                "The modlist.txt contains too many top-level mods (maximum " + MAX_TOP_LEVEL_MODS + ").");
    }

    private static Mod parseLegacyModLine(String line, int lineNumber) throws ModListTxtParseException {
        int delimiter = line.indexOf(" : ");
        String jarPart = delimiter >= 0 ? line.substring(0, delimiter).trim() : line.trim();
        String modId = delimiter >= 0 ? line.substring(delimiter + 3).trim() : null;
        boolean mCreator = containsIgnoreCase(jarPart, "(mcreator mod)");
        jarPart = removeMarker(jarPart, "(MCreator mod)");
        if (jarPart.isEmpty()) {
            throw new ModListTxtParseException("Empty jar name at line " + lineNumber + ".");
        }
        validateJarName(jarPart, lineNumber);
        return new Mod(
                jarPart, emptyToNull(modId), null, null,
                mCreator ? Boolean.TRUE : null, null,
                new HashSet<String>(), new ArrayList<Mod>(), null, null, null);
    }

    private static boolean looksLikeTableHeader(String line) {
        if (line.indexOf('|') < 0) {
            return false;
        }
        String[] cells = splitTableLine(line);
        return cells.length > 0 && "jar name".equalsIgnoreCase(cells[0].trim());
    }

    private static String[] splitTableLine(String line) {
        return line.split("\\|", -1);
    }

    private static String normalizeHeader(String value) {
        return value.trim().toLowerCase(Locale.ROOT).replaceAll("\\s+", " ");
    }

    private static Integer firstColumn(Map<String, Integer> columns, String... names) {
        for (String name : names) {
            Integer index = columns.get(name);
            if (index != null) {
                return index;
            }
        }
        return null;
    }

    private static String firstCell(String[] cells, Map<String, Integer> columns, String... names) {
        for (String name : names) {
            String value = cell(cells, columns, name);
            if (!value.isEmpty()) {
                return value;
            }
        }
        return "";
    }

    private static String cell(String[] cells, Map<String, Integer> columns, String name) {
        Integer index = columns.get(name);
        if (index == null || index.intValue() >= cells.length) {
            return "";
        }
        return cells[index.intValue()].trim();
    }

    private static Long parseLongOrNull(String value, int lineNumber) throws ModListTxtParseException {
        if (value == null || value.trim().isEmpty()) {
            return null;
        }
        try {
            return Long.valueOf(value.trim());
        } catch (NumberFormatException e) {
            throw new ModListTxtParseException("Invalid CurseForge hash at line " + lineNumber + ".", e);
        }
    }

    private static int firstContentLine(String[] lines, int start) {
        for (int i = start; i < lines.length; i++) {
            if (!lines[i].trim().isEmpty()) {
                return i;
            }
        }
        return -1;
    }

    private static boolean isSeparator(String line) {
        String compact = line.replace(" ", "");
        return !compact.isEmpty() && compact.matches("[-+]+$");
    }

    private static String removeMarker(String value, String marker) {
        if (value == null) {
            return null;
        }
        return value.replace(marker, "").replace(marker.toLowerCase(Locale.ROOT), "").trim();
    }

    private static boolean containsIgnoreCase(String value, String expected) {
        return value != null && value.toLowerCase(Locale.ROOT).contains(expected.toLowerCase(Locale.ROOT));
    }

    private static String emptyToNull(String value) {
        return value == null || value.trim().isEmpty() ? null : value.trim();
    }

    private static boolean looksLikeTopLevelEntry(String name) {
        String lower = name.toLowerCase(Locale.ROOT);
        return lower.endsWith(".jar")
                || lower.endsWith(".jar.disabled")
                || lower.endsWith("(modloader)")
                || lower.endsWith("(resourcepack)")
                || lower.endsWith("(datapack)");
    }

    private static void validateJarName(String jarName, int lineNumber) throws ModListTxtParseException {
        try {
            ModListUtils.resolveDirectModFile(jarName);
        } catch (IllegalArgumentException e) {
            throw new ModListTxtParseException(
                    "Invalid jar name at line " + lineNumber
                            + ": only a file directly inside the configured mods folder is allowed.", e);
        }
    }

    public static final class ModListTxtParseException extends IOException {
        public ModListTxtParseException(String message) {
            super(message);
        }

        public ModListTxtParseException(String message, Throwable cause) {
            super(message, cause);
        }
    }
}
