package dev.kostromdan.mods.crash_assistant.common_config.scripts.script_utils;

import dev.kostromdan.mods.crash_assistant.common_config.mod_list.Mod;

/**
 * Represents a warning generated by scripts.
 * Acts as a DTO (Data Transfer Object) to be converted into KnownCrashReason in the App module.
 */
public class ScriptWarning {
    private final String message;
    
    // Configuration
    private int priority = 10000;
    private String dontShowAgainKey = null;
    private int okDelay = 0; // seconds

    // Mod Actions
    private Mod affectedMod = null;
    private boolean showRemoveButton = false;
    private boolean showDisableButton = false;
    private boolean showExplorerButton = false;

    public ScriptWarning(String message) {
        this.message = message;
    }

    // --- Fluent API ---

    public ScriptWarning withPriority(int priority) {
        this.priority = priority;
        return this;
    }

    public ScriptWarning withDontShowAgain(String configKey) {
        this.dontShowAgainKey = configKey;
        return this;
    }

    public ScriptWarning withOkDelay(int seconds) {
        this.okDelay = seconds;
        return this;
    }

    /**
     * Enables standard mod management buttons (Remove, Disable, Show in Explorer) 
     * for the specified mod, similar to details in IncompatibleModsWarning.
     * The OK/Close button is always present.
     */
    public ScriptWarning withModActions(Mod mod) {
        this.affectedMod = mod;
        this.showRemoveButton = true;
        this.showDisableButton = true;
        this.showExplorerButton = true;
        return this;
    }
    
    // Granular control
    public ScriptWarning withRemoveButton(boolean enable) {
        this.showRemoveButton = enable;
        return this;
    }
    
    public ScriptWarning withDisableButton(boolean enable) {
        this.showDisableButton = enable;
        return this;
    }
    
    public ScriptWarning withExplorerButton(boolean enable) {
        this.showExplorerButton = enable;
        return this;
    }

    // --- Getters ---

    public String getMessage() {
        return message;
    }

    public int getPriority() {
        return priority;
    }

    public String getDontShowAgainKey() {
        return dontShowAgainKey;
    }

    public int getOkDelay() {
        return okDelay;
    }

    public Mod getAffectedMod() {
        return affectedMod;
    }

    public boolean isShowRemoveButton() {
        return showRemoveButton;
    }
    
    public boolean isShowDisableButton() {
        return showDisableButton;
    }
    
    public boolean isShowExplorerButton() {
        return showExplorerButton;
    }
}
