modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/KostromDan/Crash-Assistant/issues"
license = "KostromDan’s Modded Minecraft License (Version 1.1.3)"

[[mods]]
modId = "crash_assistant"
version = "${version}"
displayName = "Crash Assistant"
authors = "KostromDan"
description = '''
Shows a GUI after Minecraft crashes, immediately showing all affected logs, crash reports, or hs_err files. Provides a one-click solution to upload them, copy the link, and perform other actions for easier reporting, debugging, and troubleshooting.
'''
logoFile = "crash_assistant_logo.png"

[[dependencies.crash_assistant]]
modId = "neoforge"
type = "required"
mandatory = true
versionRange = "[20.5,20.6)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crash_assistant]]
modId = "minecraft"
type = "required"
mandatory = true
versionRange = "[1.20.5,1.20.6)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "crash_assistant.mixins.json"
[[mixins]]
config = "crash_assistant.neoforge.mixins.json"
