plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

dependencies {
    compileOnly files("${rootProject.projectDir}/app_common-config_libs/common_config_1_18_2__upper.jar")
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

jar {
    from("$rootDir/LICENSE.md") {
        rename { "CRASH_ASSISTANT_LICENSE.md" }
        into ""
    }
    from("$rootDir/thirdparty") {
        into "thirdparty"
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }