plugins {
    id 'com.github.johnrengelman.shadow'
    id "com.modrinth.minotaur" version "2.+"
    id "net.darkhax.curseforgegradle" version "1.1.+"
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"
    shadowBundle project(path: ':forge')
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

shadowJar {
    archiveClassifier.set('dev-shadow')
    configurations = [project.configurations.shadowBundle]

    manifest {
        attributes(
                'MixinConfigs': 'crash_assistant.mixins.json,crash_assistant-forge.mixins.json'
        )
    }
}

tasks.withType(Jar).configureEach {
    manifest {
        attributes('Automatic-Module-Name': 'dev.kostromdan.mods.crash_assistant.core_mod')
    }
}

remapJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn(':forge:build')
    from(zipTree(project(':forge').tasks.remapJar.archiveFile.get().asFile)) {
        include 'META-INF/mods.toml'
        into ''
    }

    input.set shadowJar.archiveFile
}

def publishingGameVersions = ["1.16.1", "1.16.2", "1.16.3", "1.16.4", "1.16.5"]
def parsedChangelog = file('../changelog.md').text.replaceAll(/\r\n|\r/, '\n').split(/(?:^|\n\n)\S.*?(?:\n\n|$)/)[1].trim() +
        "\n\n### [See full changelog](https://kostromdan.github.io/Crash-Assistant/changelog.md)"

if (System.getenv("MODRINTH_TOKEN") != null) {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = "ix1qq8Ux"
        versionNumber = mod_version
        versionName = tasks.remapJar.archiveFile.get().asFile.name
        versionType = release_type
        changelog = parsedChangelog
        uploadFile = tasks.remapJar
        gameVersions = publishingGameVersions
        loaders = ["forge"]
    }
}

if (System.getenv("CF_TOKEN") != null) {
    tasks.register("publishCurseForge", net.darkhax.curseforgegradle.TaskPublishCurseForge) {
        group = "upload"
        apiToken = System.getenv("CF_TOKEN")

        def mainFile = upload("1154099", tasks.remapJar)
        mainFile.displayName = tasks.remapJar.archiveFile.get().asFile.name
        mainFile.changelog = parsedChangelog
        mainFile.changelogType = "markdown"
        mainFile.releaseType = release_type

        mainFile.addGameVersion(*publishingGameVersions)
        mainFile.addEnvironment("Client")
        mainFile.addModLoader("Forge")
    }
}

task publishUnified {
    group = "upload"
    if (System.getenv("MODRINTH_TOKEN") != null) dependsOn(tasks.modrinth)
    if (System.getenv("CF_TOKEN") != null) dependsOn(tasks.publishCurseForge)
}

task publishUnifiedToLocal(type: Copy) {
    group = "upload"
    dependsOn(tasks.remapJar)
    from(tasks.remapJar.archiveFile)
    into("build/unified-local/project0")
}
