plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id "com.modrinth.minotaur" version "2.+"
    id "net.darkhax.curseforgegradle" version "1.1.+"
}

base {
    archivesName = "CrashAssistant-forge-1.21.5-1.21.11"
}

configurations {
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier.set('dev-shadow')
}

tasks.withType(Jar).configureEach {
    manifest {
        attributes('Automatic-Module-Name': 'dev.kostromdan.mods.crash_assistant.core_mod')
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn(':forge:build')
    dependsOn tasks.shadowJar

    from zipTree("${rootProject.projectDir}/app_common-config_libs/common_config_1_18_2__upper.jar")
    from zipTree(tasks.shadowJar.archiveFile.get().asFile)
    from(project(':forge').tasks.jar) {
        rename { "crash_assistant-forge.jar" }
        into 'META-INF/jarjar'
    }
    from(zipTree(project(':forge').tasks.jar.archiveFile.get().asFile)) {
        include 'META-INF/mods.toml'
        into ''
    }
    exclude("crash_assistant.mixins.json")
    exclude("crash_assistant.forge.mixins.json")
    exclude("dev/kostromdan/mods/crash_assistant/forge/**")
    exclude("dev/kostromdan/mods/crash_assistant/common/**")
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    copyIdeResources = true //Calls processResources when in dev

    reobf = false // Forge 1.20.6+ uses official mappings at runtime, so we shouldn't reobf from official to SRG

    runs {
        client {
            workingDirectory file('runs/client')
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Client'
            mods {
                modClientRun {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory file('runs/server')
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Server'
            mods {
                modServerRun {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory file('runs/data')
            ideaModule "${rootProject.name}.${project.name}.main"
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
            taskName 'Data'
            mods {
                modDataRun {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")

    // Forge's hack fix
    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }
    compileOnly files("${rootProject.projectDir}/app_common-config_libs/common_config_1_18_2__upper.jar")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            fg.component(it)
        }
    }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

def publishingGameVersions = [
        "1.21.5",
        "1.21.6",
        "1.21.7",
        "1.21.8",
        "1.21.9",
        "1.21.10",
        "1.21.11"
]
def parsedChangelog = file('../changelog.md').text.replaceAll(/\r\n|\r/, '\n').split(/(?:^|\n\n)\S.*?(?:\n\n|$)/)[1].trim() +
        "\n\n### [See full changelog](https://kostromdan.github.io/Crash-Assistant/changelog.md)"

if (System.getenv("MODRINTH_TOKEN") != null) {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = "ix1qq8Ux"
        versionNumber = project.version
        versionName = tasks.jar.archiveFile.get().asFile.name
        versionType = release_type
        changelog = parsedChangelog
        uploadFile = tasks.jar
        gameVersions = publishingGameVersions
        loaders = ["forge"]
    }
}

if (System.getenv("CF_TOKEN") != null) {
    tasks.register("publishCurseForge", net.darkhax.curseforgegradle.TaskPublishCurseForge) {
        group = "upload"
        apiToken = System.getenv("CF_TOKEN")

        def mainFile = upload("1154099", tasks.jar)
        mainFile.displayName = tasks.jar.archiveFile.get().asFile.name
        mainFile.changelog = parsedChangelog
        mainFile.changelogType = "markdown"
        mainFile.releaseType = release_type

        mainFile.addGameVersion(*publishingGameVersions)
        mainFile.addEnvironment("Client")
        mainFile.addModLoader("Forge")
    }
}

task publishUnified {
    group = "upload"
    if (System.getenv("MODRINTH_TOKEN") != null) dependsOn(tasks.modrinth)
    if (System.getenv("CF_TOKEN") != null) dependsOn(tasks.publishCurseForge)
}

task publishUnifiedToLocal(type: Copy) {
    group = "upload"
    dependsOn(tasks.jar)
    from(tasks.jar.archiveFile)
    into("build/unified-local/project0")
}
