plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id "me.shedaniel.unified-publishing" version "0.1.+"
}

base {
    archivesName = "CrashAssistant-forge-1.21.5-1.21.10"
}

configurations {
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier.set('dev-shadow')
    relocate 'com.electronwill.nightconfig', 'dev.kostromdan.mods.crash_assistant.nightconfig'
}

tasks.withType(Jar).configureEach {
    manifest {
        attributes('Automatic-Module-Name': 'dev.kostromdan.mods.crash_assistant.core_mod')
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    dependsOn(':app:shadowJar', ':forge:build')
    dependsOn tasks.shadowJar

    from("$rootDir/LICENSE.md") {
        rename { "CRASH_ASSISTANT_LICENSE.md" }
        into ""
    }
    from("$rootDir/thirdparty") {
        into "thirdparty"
    }

    from zipTree(tasks.shadowJar.archiveFile.get().asFile)
    from(project(':app').tasks.shadowJar) {
        into 'META-INF/jarjar'
    }
    from(project(':forge').tasks.jar) {
        rename { "crash_assistant-forge.jar" }
        into 'META-INF/jarjar'
    }
    from(zipTree(project(':forge').tasks.jar.archiveFile.get().asFile)) {
        include 'META-INF/mods.toml'
        into ''
    }
    exclude("crash_assistant.mixins.json")
    exclude("crash_assistant.forge.mixins.json")
    exclude("dev/kostromdan/mods/crash_assistant/forge/**")
    exclude("dev/kostromdan/mods/crash_assistant/common/**")
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    copyIdeResources = true //Calls processResources when in dev

    reobf = false // Forge 1.20.6+ uses official mappings at runtime, so we shouldn't reobf from official to SRG

    runs {
        client {
            workingDirectory file('runs/client')
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Client'
            mods {
                modClientRun {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory file('runs/server')
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Server'
            mods {
                modServerRun {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory file('runs/data')
            ideaModule "${rootProject.name}.${project.name}.main"
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
            taskName 'Data'
            mods {
                modDataRun {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")

    // Forge's hack fix
    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }
    shadowBundle 'com.electronwill.night-config:toml:3.6.4'
    shadowBundle 'com.electronwill.night-config:json:3.6.4'
    compileOnly project(path: ':common_config')
    shadowBundle project(path: ':common_config')
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            fg.component(it)
        }
    }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

unifiedPublishing {
    project {
        gameVersions = [
                "1.21.5",
                "1.21.6",
                "1.21.7",
                "1.21.8",
                "1.21.9",
                "1.21.10"
        ]
        gameLoaders = ["forge"]

        displayName = tasks.jar.archiveFile.get().asFile.name
        version = project.version
        changelog = file('../changelog.md').text
        releaseType = release_type

        mainPublication tasks.jar

        var cfToken = System.getenv("CF_TOKEN")
        if (cfToken != null) {
            curseforge {
                token = cfToken
                id = "1154099"
            }
        }

        var mrToken = System.getenv("MODRINTH_TOKEN")
        if (mrToken != null) {
            modrinth {
                token = mrToken
                id = "ix1qq8Ux"
            }
        }
    }
}